export default [
  {
    team_id: 12518,
    name: "Argentina",
    short_code: "ARG",
    common_name: "Argentina",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/6939.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2067,
    group_name: "C",
  },
  {
    team_id: 747,
    name: "Australia",
    short_code: "AUS",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/243.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2068,
    group_name: "D",
  },
  {
    team_id: 3054,
    name: "Belgium",
    short_code: "BEL",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/27.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2070,
    group_name: "F",
  },
  {
    team_id: 12556,
    name: "Brazil",
    short_code: "BRA",
    common_name: "Brazil",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/3723.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2071,
    group_name: "G",
  },
  {
    team_id: 85,
    name: "Cameroon",
    short_code: "CMR",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/1428.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2071,
    group_name: "G",
  },
  {
    team_id: 7835,
    name: "Canada",
    short_code: "CAN",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/225.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2070,
    group_name: "F",
  },
  {
    team_id: 7841,
    name: "Costa Rica",
    short_code: "CRC",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/235.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2069,
    group_name: "E",
  },
  {
    team_id: 3026,
    name: "Croatia",
    short_code: "CRO",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/30.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2070,
    group_name: "F",
  },
  {
    team_id: 3008,
    name: "Denmark",
    short_code: "DEN",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/25.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2068,
    group_name: "D",
  },
  {
    team_id: 12551,
    name: "Ecuador",
    short_code: "ECU",
    common_name: "Ecuador",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/9766.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2065,
    group_name: "A",
  },
  {
    team_id: 12506,
    name: "England",
    short_code: "ENG",
    common_name: "England",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/7623.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2066,
    group_name: "B",
  },
  {
    team_id: 12508,
    name: "France",
    short_code: "FRA",
    common_name: "France",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/7627.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2068,
    group_name: "D",
  },
  {
    team_id: 3017,
    name: "Germany",
    short_code: "GER",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/36.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2069,
    group_name: "E",
  },
  {
    team_id: 95,
    name: "Ghana",
    short_code: "GHA",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/1429.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2072,
    group_name: "H",
  },
  {
    team_id: 12396,
    name: "Iran",
    short_code: "IRI",
    common_name: "Iran",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/242.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2066,
    group_name: "B",
  },
  {
    team_id: 12397,
    name: "Japan",
    short_code: "JPN",
    common_name: "Japan",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/251.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2069,
    group_name: "E",
  },
  {
    team_id: 12513,
    name: "Mexico",
    short_code: "MEX",
    common_name: "Mexico",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/9655.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2067,
    group_name: "C",
  },
  {
    team_id: 52,
    name: "Morocco",
    short_code: "MAR",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/241.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2070,
    group_name: "F",
  },
  {
    team_id: 3080,
    name: "Netherlands",
    short_code: "NED",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/31.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2065,
    group_name: "A",
  },
  {
    team_id: 3011,
    name: "Poland",
    short_code: "POL",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/40.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2067,
    group_name: "C",
  },
  {
    team_id: 12507,
    name: "Portugal",
    short_code: "POR",
    common_name: "Portugal",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/7625.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2072,
    group_name: "H",
  },
  {
    team_id: 12509,
    name: "Qatar",
    short_code: "QAT",
    common_name: "Qatar",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/7628.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2065,
    group_name: "A",
  },
  {
    team_id: 755,
    name: "Republic of Korea",
    short_code: "KOR",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/248.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2072,
    group_name: "H",
  },
  {
    team_id: 767,
    name: "Saudi Arabia",
    short_code: "KSA",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/238.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2067,
    group_name: "C",
  },
  {
    team_id: 56,
    name: "Senegal",
    short_code: "SEN",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/252.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2065,
    group_name: "A",
  },
  {
    team_id: 3036,
    name: "Serbia",
    short_code: "SRB",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/160.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2071,
    group_name: "G",
  },
  {
    team_id: 3024,
    name: "Spain",
    short_code: "ESP",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/33.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2069,
    group_name: "E",
  },
  {
    team_id: 3064,
    name: "Switzerland",
    short_code: "SUI",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/24.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2071,
    group_name: "G",
  },
  {
    team_id: 73,
    name: "Tunisia",
    short_code: "TUN",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/249.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2068,
    group_name: "D",
  },
  {
    team_id: 7850,
    name: "USA",
    short_code: "USA",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/232.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2066,
    group_name: "B",
  },
  {
    team_id: 12554,
    name: "Uruguay",
    short_code: "URU",
    common_name: "Uruguay",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/9769.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2072,
    group_name: "H",
  },
  {
    team_id: 3040,
    name: "Wales",
    short_code: "WAL",
    common_name: "",
    logo: "https://cdn.sportdataapi.com/images/soccer/teams/100/23.png",
    country: {
      country_id: 7,
      name: "World",
      country_code: null,
      continent: "World",
    },
    group_id: 2066,
    group_name: "B",
  },
];
